// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMethodDescriminator.Infrastructure.Data;

#nullable disable

namespace PaymentMethodDescriminator.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PaymentMethodDescriminator.Domain.Entities.CategoryPaymentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("PaymentMethodType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CategoryPaymentRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Food",
                            IsActive = true,
                            PaymentMethodType = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Food",
                            IsActive = true,
                            PaymentMethodType = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            IsActive = true,
                            PaymentMethodType = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            IsActive = true,
                            PaymentMethodType = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
